# This is a basic workflow to help you get started with Actions

name: pull data and retrain model

on:
  schedule:
    - cron: '*/5 * * * *' # runs at 12:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2 
    
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.12' 
      
      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: pull data
        env: 
          fred_key: ${{ secrets.FRED_KEY }}
        run: python pull_data.py
        
      - name: re-train
        run: python train.py
